spring:
#  config:
#    activate:
#      on-profile: dev
  application:
    name: REVIRAL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviral
    username: root
    password: rlgus585
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 56ac35134c8382f04cbc27e9190f7cd5
            client-secret: c8QUId8lp5mkvwMNNq4Un2990Giz26n0
            admin-key: 2f4f76a882821ea48b8afba3e0366c77
            redirect-uri: http://172.30.1.106:3000/login/auth/kakao
            response-type: code
            authorization-grant-type: authorization_code
            client-name: KAKAO
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: Iky9dTxrXQZbeYYBUWBC
            client-secret: NURFJsf_yy
            redirect-uri: http://172.30.1.106:3000/login/auth/naver
            response-type: code
            authorization-grant-type: authorization_code
            client-name: NAVER
            scope:
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: true #SQL 로그 설정
        format_sql: true #SQL 포맷 설정
        use_sql_comments: false #SQL 코멘트 사용
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    username: reviralcompany@gmail.com
    password: pfugdgbrtbdepssx
    properties:
      debug: true
      smtp.ssl.enable: true
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 5MB
      max-request-size: 10MB