spring:
  config:
    activate:
      on-profile: dev
  application:
    name: REVIRAL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cv8rhcd6l47c73fre9b0-a/reviral_database
    username: reviral_database_user
    password: yl2t48B3GmTWnueDV2hRJl56jR6zaBKJ
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 56ac35134c8382f04cbc27e9190f7cd5
            client-secret: c8QUId8lp5mkvwMNNq4Un2990Giz26n0
            admin-key: 2f4f76a882821ea48b8afba3e0366c77
            redirect-uri: http://172.30.1.106:3000/login/auth/kakao
            response-type: code
            authorization-grant-type: authorization_code
            client-name: KAKAO
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: Iky9dTxrXQZbeYYBUWBC
            client-secret: NURFJsf_yy
            redirect-uri: http://172.30.1.106:3000/login/auth/naver
            response-type: code
            authorization-grant-type: authorization_code
            client-name: NAVER
            scope:
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response